### ISSUE TITLE
Is there a limit on how many it will fetch?

### ISSUE THREAD

**Issue by subratom** [pixelandtonic/CategorySources#7]
I have a lot of taxonomy items and only half of them show up. Is there a reason why that would happen?

**Comment by angrybrad** [comment]
For now you'd probably need to add a `$criteria->limit = null` right around here: `https://github.com/pixelandtonic/CategorySources/blob/master/categorysources/CategorySourcesPlugin.php#L141

Don't want to add that to the source, though as it should probably be a plugin settings.
